# Generated by Django 4.2.19 on 2025-03-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
